# Generated by Django 2.1.3 on 2018-12-10 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='result_accuracy_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
